## Tarea 1 Opti repitis

In [1]:
import numpy as np
from scipy.optimize import minimize, Bounds

In [2]:
## Funcion a optimizar

def costo(X):
    
    C = np.array([[99999,0.3,99999,99999,1.2,1.2,1.4],[99999,99999,0.2,0.15,99999,99999,99999],[99999,99999,99999,99999,0.25,0.2,0.15],[99999,99999,99999,99999,0.22,0.2,0.15],[99999,99999,99999,99999,99999,99999,99999],[99999,99999,99999,99999,99999,99999,99999],[99999,99999,99999,99999,99999,99999,99999]])
    C= C.reshape(49)
    return np.sum(np.multiply(X,C))    
    

In [3]:
C = np.array([[10000,0.3,10000,10000,1.2,1.2,1.4],[10000,10000,0.2,0.15,10000,10000,10000],[10000,10000,10000,10000,0.25,0.2,0.15],[10000,10000,10000,10000,0.22,0.2,0.15],[10000,10000,10000,10000,10000,10000,10000],[10000,10000,10000,10000,10000,10000,10000],[10000,10000,10000,10000,10000,10000,10000]])
print(C)

[[1.0e+04 3.0e-01 1.0e+04 1.0e+04 1.2e+00 1.2e+00 1.4e+00]
 [1.0e+04 1.0e+04 2.0e-01 1.5e-01 1.0e+04 1.0e+04 1.0e+04]
 [1.0e+04 1.0e+04 1.0e+04 1.0e+04 2.5e-01 2.0e-01 1.5e-01]
 [1.0e+04 1.0e+04 1.0e+04 1.0e+04 2.2e-01 2.0e-01 1.5e-01]
 [1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04]
 [1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04]
 [1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04 1.0e+04]]


In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[2,2,2],[1,1,1]])

In [5]:
np.sum(np.multiply(A,B)) #Con multiply, no importa si las matrices estan definidas como matrix o array se hace la mult punto a punto

68

In [36]:
Ar = A.reshape(9)
Arr = Ar.reshape(3,3)

In [37]:
print(A)
print(Ar)
print(Arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
X0 = np.random.rand(7,7)
X0=X0.reshape(49)

In [9]:
X0

array([0.48437357, 0.73745591, 0.01301705, 0.84776014, 0.02535363,
       0.85136753, 0.26579423, 0.003153  , 0.30495421, 0.10022565,
       0.27991116, 0.28373303, 0.50966187, 0.98470312, 0.40668143,
       0.41431943, 0.545942  , 0.66209131, 0.75592051, 0.93048494,
       0.58482484, 0.41029202, 0.1875211 , 0.76770037, 0.26277142,
       0.69109339, 0.92948567, 0.26649894, 0.90074859, 0.22331569,
       0.11655974, 0.40453059, 0.8119781 , 0.08110861, 0.62310043,
       0.57291835, 0.27878483, 0.38105351, 0.29332865, 0.53860017,
       0.16406414, 0.31747982, 0.62746296, 0.66335235, 0.0887815 ,
       0.91768728, 0.0410513 , 0.9625129 , 0.40398525])

In [10]:
X0[48]

0.403985248012501

In [11]:
def constraint1(X):
    return 0.7*20e6 - X[1] #Desiguladad

def constraint2(X):
    return 10e6 - X[10] #Desigualdad

def constraint3(X):
    suma = 20e6 #Valor de la constante a igualar
    for j in range(7):
        suma = suma - X[j] #Igualdad   
    return suma

def constraint4(X):
    suma = 4e6 #Valor de la constante a igualar
    for i in range(7):
        suma = suma - X[4+(7*i)]
    return suma

def constraint5(X):
    suma = 12e6 #Valor de la constante a igualar
    for i in range(7):
        suma = suma - X[5+(7*i)]
    return suma

def constraint6(X):
    suma = 4e6 #Valor de la constante a igualar
    for i in range(7):
        suma = suma - X[6+(7*i)]
    return suma

In [12]:
#Definicion de limites sueprior e inferior

b = [(0,20000000)]*49

bnds = (b)

#print(bnds)
#bnds = Bounds(bnds)
con1 = {'type': 'ineq','fun': constraint1}
con2 = {'type': 'ineq','fun': constraint2}
con3 = {'type': 'eq','fun': constraint3}
con4 = {'type': 'eq','fun': constraint4}
con5 = {'type': 'eq','fun': constraint5}
con6 = {'type': 'eq','fun': constraint6}

cons = [con1,con2,con3,con4,con5,con6]

In [13]:
#(b)

In [14]:
sol = minimize(costo,X0,method='SLSQP',bounds=bnds,constraints=cons)

In [15]:
sol.fun

21439341.640291262

In [ ]:
costo(sol.x)

In [16]:
sol.x

array([0.00000000e+00, 4.80083943e+06, 0.00000000e+00, 0.00000000e+00,
       3.99932761e+06, 7.20056958e+06, 3.99932762e+06, 0.00000000e+00,
       0.00000000e+00, 3.40552442e-10, 1.23481242e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.39530510e+02, 2.39973266e+06,
       3.39279421e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.39530386e+02, 2.39973265e+06, 3.39778780e+02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [17]:
solucion = sol.x.reshape(7,7)

In [38]:
solucion

array([[0.00000000e+00, 4.80083943e+06, 0.00000000e+00, 0.00000000e+00,
        3.99932761e+06, 7.20056958e+06, 3.99932762e+06],
       [0.00000000e+00, 0.00000000e+00, 3.40552442e-10, 1.23481242e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.39530510e+02, 2.39973266e+06, 3.39279421e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.39530386e+02, 2.39973265e+06, 3.39778780e+02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [39]:
total=0
for i in range(7):
    total = total + sol.x[6+(7*i)]
    
print(total)

4000006.6753403638


In [72]:
np.sum(solucion[:,6])

4000006.6753403638

In [55]:
solucion.shape

(7, 7)